input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["fact-check-results"]
    codec => "json"
    auto_offset_reset => "earliest"
    group_id => "logstash-group"
  }
}

filter {
  mutate {
    remove_field => ["@version", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "fake-news-index"
  }
  stdout { codec => rubydebug }
}
